import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "FileFusion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="min-h-screen pt-20">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
